apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: emobility
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        {{- include "labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: github
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}@{{ .Values.image.sha }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.deployment.cpu.request }}
              memory: {{ .Values.deployment.memory.request }}
            limits:
              cpu: {{ .Values.deployment.cpu.limit }}
              memory: {{ .Values.deployment.memory.limit }}
          livenessProbe:
            httpGet:
              path: /playground/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /playground/index.html
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Chart.Name }}
              topologyKey: topology.kubernetes.io/zone

