apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: emobility
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Chart.Name }}
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
  type: NodePort