name: e2e-integration-tests-workflow

on: [workflow_dispatch]

jobs:
  e2e-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print message
        run: echo "e2e/integration tests"